pip install _ipyw_jlab_nb_ext_conf -U
pip install alabaster -U
pip install anaconda -U
pip install anaconda-client -U
pip install anaconda-navigator -U
pip install anaconda-project -U
pip install argh -U
pip install asn1crypto -U
pip install astroid -U
pip install astropy -U
pip install atomicwrites -U
pip install attrs -U
pip install autopep8 -U
pip install babel -U
pip install backcall -U
pip install backports -U
pip install backports.functools_lru_cache -U
pip install backports.shutil_get_terminal_size -U
pip install backports.tempfile -U
pip install backports.weakref -U
pip install bcrypt -U
pip install beautifulsoup4 -U
pip install bitarray -U
pip install bkcharts -U
pip install blas -U
pip install bleach -U
pip install blosc -U
pip install bokeh -U
pip install boto -U
pip install bottleneck -U
pip install brotlipy -U
pip install bzip2 -U
pip install ca-certificates -U
pip install certifi -U
pip install cffi -U
pip install chardet -U
pip install click -U
pip install cloudpickle -U
pip install clyent -U
pip install colorama -U
pip install comtypes -U
pip install conda -U
pip install conda-build -U
pip install conda-env -U
pip install conda-package-handling -U
pip install conda-verify -U
pip install console_shortcut -U
pip install contextlib2 -U
pip install cryptography -U
pip install curl -U
pip install cycler -U
pip install cython -U
pip install cytoolz -U
pip install dask -U
pip install dask-core -U
pip install decorator -U
pip install defusedxml -U
pip install diff-match-patch -U
pip install distributed -U
pip install docutils -U
pip install entrypoints -U
pip install et_xmlfile -U
pip install fastcache -U
pip install filelock -U
pip install flake8 -U
pip install flask -U
pip install freetype -U
pip install fsspec -U
pip install future -U
pip install get_terminal_size -U
pip install gevent -U
pip install glob2 -U
pip install gmpy2 -U
pip install greenlet -U
pip install h5py -U
pip install hdf5 -U
pip install heapdict -U
pip install html5lib -U
pip install icc_rt -U
pip install icu -U
pip install idna -U
pip install imageio -U
pip install imagesize -U
pip install importlib-metadata -U
pip install importlib_metadata -U
pip install intel-openmp -U
pip install intervaltree -U
pip install ipykernel -U
pip install ipython -U
pip install ipython_genutils -U
pip install ipywidgets -U
pip install isort -U
pip install itsdangerous -U
pip install jdcal -U
pip install jedi -U
pip install jinja2 -U
pip install joblib -U
pip install jpeg -U
pip install json5 -U
pip install jsonschema -U
pip install jupyter -U
pip install jupyter_client -U
pip install jupyter_console -U
pip install jupyter_core -U
pip install jupyterlab -U
pip install jupyterlab_server -U
pip install keyring -U
pip install kiwisolver -U
pip install krb5 -U
pip install lazy-object-proxy -U
pip install libarchive -U
pip install libcurl -U
pip install libiconv -U
pip install liblief -U
pip install libllvm9 -U
pip install libpng -U
pip install libsodium -U
pip install libspatialindex -U
pip install libssh2 -U
pip install libtiff -U
pip install libxml2 -U
pip install libxslt -U
pip install llvmlite -U
pip install locket -U
pip install lxml -U
pip install lz4-c -U
pip install lzo -U
pip install m2w64-gcc-libgfortran -U
pip install m2w64-gcc-libs -U
pip install m2w64-gcc-libs-core -U
pip install m2w64-gmp -U
pip install m2w64-libwinpthread-git -U
pip install markupsafe -U
pip install matplotlib -U
pip install mccabe -U
pip install menuinst -U
pip install mistune -U
pip install mkl -U
pip install mkl-service -U
pip install mkl_fft -U
pip install mkl_random -U
pip install mock -U
pip install more-itertools -U
pip install mpc -U
pip install mpfr -U
pip install mpir -U
pip install mpmath -U
pip install msgpack-python -U
pip install msys2-conda-epoch -U
pip install multipledispatch -U
pip install navigator-updater -U
pip install nb_conda_kernels -U
pip install nbconvert -U
pip install nbformat -U
pip install networkx -U
pip install nltk -U
pip install nose -U
pip install notebook -U
pip install numba -U
pip install numexpr -U
pip install numpy -U
pip install numpydoc -U
pip install olefile -U
pip install openpyxl -U
pip install openssl -U
pip install packaging -U
pip install pandas -U
pip install pandoc -U
pip install pandocfilters -U
pip install paramiko -U
pip install parso -U
pip install partd -U
pip install path -U
pip install path.py -U
pip install pathlib2 -U
pip install pathtools -U
pip install patsy -U
pip install pep8 -U
pip install pexpect -U
pip install pickleshare -U
pip install pillow -U
pip install pip -U
pip install pkginfo -U
pip install pluggy -U
pip install ply -U
pip install powershell_shortcut -U
pip install prometheus_client -U
pip install prompt-toolkit -U
pip install prompt_toolkit -U
pip install psutil -U
pip install py -U
pip install py-lief -U
pip install pyautogui -U
pip install pycodestyle -U
pip install pycosat -U
pip install pycparser -U
pip install pycurl -U
pip install pydocstyle -U
pip install pyflakes -U
pip install pygments -U
pip install pylint -U
pip install pymsgbox -U
pip install pynacl -U
pip install pyodbc -U
pip install pyopenssl -U
pip install pyparsing -U
pip install pyqt -U
pip install pyreadline -U
pip install pyrsistent -U
pip install pyscreeze -U
pip install pysocks -U
pip install pytables -U
pip install pytest -U
pip install python -U
pip install python-dateutil -U
pip install python-jsonrpc-server -U
pip install python-language-server -U
pip install python-libarchive-c -U
pip install python_abi -U
pip install pytweening -U
pip install pytz -U
pip install pywavelets -U
pip install pywin32 -U
pip install pywin32-ctypes -U
pip install pywinpty -U
pip install pyyaml -U
pip install pyzmq -U
pip install qdarkstyle -U
pip install qt -U
pip install qtawesome -U
pip install qtconsole -U
pip install qtpy -U
pip install regex -U
pip install requests -U
pip install rope -U
pip install rtree -U
pip install ruamel_yaml -U
pip install scikit-image -U
pip install scikit-learn -U
pip install scipy -U
pip install seaborn -U
pip install send2trash -U
pip install setuptools -U
pip install simplegeneric -U
pip install singledispatch -U
pip install sip -U
pip install six -U
pip install sklearn -U
pip install snappy -U
pip install snowballstemmer -U
pip install sortedcollections -U
pip install sortedcontainers -U
pip install soupsieve -U
pip install sphinx -U
pip install sphinxcontrib -U
pip install sphinxcontrib-applehelp -U
pip install sphinxcontrib-devhelp -U
pip install sphinxcontrib-htmlhelp -U
pip install sphinxcontrib-jsmath -U
pip install sphinxcontrib-qthelp -U
pip install sphinxcontrib-serializinghtml -U
pip install sphinxcontrib-websupport -U
pip install spyder -U
pip install spyder-kernels -U
pip install sqlalchemy -U
pip install sqlite -U
pip install statsmodels -U
pip install sympy -U
pip install tbb -U
pip install tblib -U
pip install terminado -U
pip install testpath -U
pip install threadpoolctl -U
pip install tk -U
pip install toml -U
pip install toolz -U
pip install tornado -U
pip install tqdm -U
pip install traitlets -U
pip install typing_extensions -U
pip install ujson -U
pip install unicodecsv -U
pip install urllib3 -U
pip install vc -U
pip install vs2015_runtime -U
pip install watchdog -U
pip install wcwidth -U
pip install webencodings -U
pip install werkzeug -U
pip install wheel -U
pip install widgetsnbextension -U
pip install win_inet_pton -U
pip install win_unicode_console -U
pip install wincertstore -U
pip install winpty -U
pip install wrapt -U
pip install xlrd -U
pip install xlsxwriter -U
pip install xlwings -U
pip install xlwt -U
pip install xmltodict -U
pip install xz -U
pip install yaml -U
pip install yapf -U
pip install zeromq -U
pip install zict -U
pip install zipp -U
pip install zlib -U
pip install zope -U
pip install zope.event -U
pip install zope.interface -U
pip install zstd -U
